/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    installations: Installation;
    repos: Repo;
    'sync-events': SyncEvent;
    'linear-integrations': LinearIntegration;
    agents: Agent;
    'durable-objects': DurableObject;
    connections: Connection;
    'tool-executions': ToolExecution;
    models: Model;
    'model-defaults': ModelDefault;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      installations: 'installations';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    installations: InstallationsSelect<false> | InstallationsSelect<true>;
    repos: ReposSelect<false> | ReposSelect<true>;
    'sync-events': SyncEventsSelect<false> | SyncEventsSelect<true>;
    'linear-integrations': LinearIntegrationsSelect<false> | LinearIntegrationsSelect<true>;
    agents: AgentsSelect<false> | AgentsSelect<true>;
    'durable-objects': DurableObjectsSelect<false> | DurableObjectsSelect<true>;
    connections: ConnectionsSelect<false> | ConnectionsSelect<true>;
    'tool-executions': ToolExecutionsSelect<false> | ToolExecutionsSelect<true>;
    models: ModelsSelect<false> | ModelsSelect<true>;
    'model-defaults': ModelDefaultsSelect<false> | ModelDefaultsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'user')[];
  /**
   * GitHub user ID
   */
  githubId?: number | null;
  /**
   * GitHub username
   */
  githubLogin?: string | null;
  /**
   * GitHub avatar URL
   */
  githubAvatarUrl?: string | null;
  /**
   * Display name
   */
  name?: string | null;
  /**
   * WorkOS user ID
   */
  workosUserId?: string | null;
  installations?: {
    docs?: (number | Installation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "installations".
 */
export interface Installation {
  id: number;
  /**
   * GitHub App installation ID
   */
  installationId: number;
  /**
   * GitHub account ID (user or org)
   */
  accountId: number;
  /**
   * GitHub account login (username or org name)
   */
  accountLogin: string;
  accountType: 'User' | 'Organization';
  /**
   * GitHub avatar URL
   */
  accountAvatarUrl?: string | null;
  /**
   * Granted permissions from GitHub
   */
  permissions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Subscribed webhook events
   */
  events?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  repositorySelection?: ('all' | 'selected') | null;
  /**
   * When the installation was suspended
   */
  suspendedAt?: string | null;
  /**
   * Users connected to this installation
   */
  users?: (number | User)[] | null;
  /**
   * Tool configuration for all repos in this installation
   */
  toolConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Default approval gate settings for all repos in this installation
   */
  approvalGates?: {
    /**
     * Require human approval before merging PRs (default for all repos)
     */
    requireHumanApproval?: boolean | null;
    /**
     * Allow fully autonomous operation (no human approval required)
     */
    allowFullAutonomy?: boolean | null;
    /**
     * Maximum daily budget in USD for agent operations
     */
    maxBudgetPerDay?: number | null;
    /**
     * Rate limit: max agent spawns per hour
     */
    maxAgentSpawnsPerHour?: number | null;
    /**
     * Risk threshold for automatic approval
     */
    riskThreshold?: ('low' | 'medium' | 'high') | null;
    /**
     * File paths that always require human approval (glob patterns)
     */
    criticalPaths?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Issue labels that allow automatic merge without human approval
     */
    autoApproveLabels?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Issue labels that always require human approval
     */
    requireApprovalLabels?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Conditions that trigger approval requirements (org-wide defaults)
     */
    triggers?: {
      /**
       * PR/issue labels that trigger approval
       */
      labels?:
        | {
            label: string;
            id?: string | null;
          }[]
        | null;
      /**
       * Issue types that trigger approval
       */
      types?:
        | {
            type: 'task' | 'bug' | 'feature' | 'epic';
            id?: string | null;
          }[]
        | null;
      /**
       * File path patterns that trigger approval (glob patterns)
       */
      filesChanged?:
        | {
            /**
             * Glob pattern (e.g., src/auth/**, *.sql)
             */
            pattern: string;
            id?: string | null;
          }[]
        | null;
      /**
       * Risk score threshold (0-100) that triggers approval
       */
      riskScore?: number | null;
    };
    /**
     * GitHub usernames who can approve (org-wide default)
     */
    approvers?:
      | {
          /**
           * GitHub username
           */
          username: string;
          id?: string | null;
        }[]
      | null;
    /**
     * GitHub teams who can approve (format: org/team-slug)
     */
    teamApprovers?:
      | {
          /**
           * GitHub team in format: org/team-slug
           */
          team: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "repos".
 */
export interface Repo {
  id: number;
  /**
   * GitHub repository ID
   */
  githubId: number;
  /**
   * Repository name (without owner)
   */
  name: string;
  /**
   * Full name (owner/repo)
   */
  fullName: string;
  /**
   * Repository owner (user or org login)
   */
  owner: string;
  private?: boolean | null;
  defaultBranch?: string | null;
  installation: number | Installation;
  /**
   * Whether to sync issues with GitHub
   */
  syncEnabled?: boolean | null;
  /**
   * Path to todo.mdx file in the repo
   */
  syncPath?: string | null;
  /**
   * Last successful sync timestamp
   */
  lastSyncAt?: string | null;
  syncStatus?: ('idle' | 'syncing' | 'error') | null;
  /**
   * Last sync error message
   */
  syncError?: string | null;
  /**
   * PR code review configuration
   */
  reviewConfig?: {
    /**
     * Whether PR review is enabled for this repo
     */
    enabled?: boolean | null;
    /**
     * Ordered list of reviewers
     */
    reviewers?:
      | {
          /**
           * Agent to review this PR
           */
          agent: number | Agent;
          id?: string | null;
        }[]
      | null;
    /**
     * Auto-merge when all reviewers approve
     */
    autoMerge?: boolean | null;
    /**
     * Require at least one human approval
     */
    requireHumanApproval?: boolean | null;
  };
  /**
   * Approval gate settings for this repo (overrides org-level defaults)
   */
  approvalGates?: {
    /**
     * Inherit approval gate settings from organization
     */
    inheritFromOrg?: boolean | null;
    /**
     * Require human approval before merging PRs
     */
    requireHumanApproval?: boolean | null;
    /**
     * Allow fully autonomous operation (no human approval required)
     */
    allowFullAutonomy?: boolean | null;
    /**
     * Maximum daily budget in USD for this repo
     */
    maxBudgetPerDay?: number | null;
    /**
     * Rate limit: max agent spawns per hour for this repo
     */
    maxAgentSpawnsPerHour?: number | null;
    /**
     * Risk threshold for automatic approval
     */
    riskThreshold?: ('low' | 'medium' | 'high') | null;
    /**
     * Additional file paths that require human approval (glob patterns)
     */
    criticalPaths?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Issue labels that allow automatic merge without human approval
     */
    autoApproveLabels?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Issue labels that always require human approval
     */
    requireApprovalLabels?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Conditions that trigger approval requirements
     */
    triggers?: {
      /**
       * PR/issue labels that trigger approval
       */
      labels?:
        | {
            label: string;
            id?: string | null;
          }[]
        | null;
      /**
       * Issue types that trigger approval
       */
      types?:
        | {
            type: 'task' | 'bug' | 'feature' | 'epic';
            id?: string | null;
          }[]
        | null;
      /**
       * File path patterns that trigger approval (glob patterns)
       */
      filesChanged?:
        | {
            /**
             * Glob pattern (e.g., src/auth/**, *.sql)
             */
            pattern: string;
            id?: string | null;
          }[]
        | null;
      /**
       * Risk score threshold (0-100) that triggers approval
       */
      riskScore?: number | null;
    };
    /**
     * GitHub usernames who can approve
     */
    approvers?:
      | {
          /**
           * GitHub username
           */
          username: string;
          id?: string | null;
        }[]
      | null;
    /**
     * GitHub teams who can approve (format: org/team-slug)
     */
    teamApprovers?:
      | {
          /**
           * GitHub team in format: org/team-slug
           */
          team: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Tool configuration for this repository (inherits from installation)
   */
  toolConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Cost control settings and spend tracking for agent operations
   */
  costControls?: {
    /**
     * Whether cost controls are enabled for this repo
     */
    enabled?: boolean | null;
    /**
     * Inherit budget limits from organization installation
     */
    inheritFromOrg?: boolean | null;
    /**
     * Maximum monthly budget in USD for Claude API spend (overrides org-level if not inheriting)
     */
    monthlyBudget?: number | null;
    /**
     * Maximum number of agent sessions per day (overrides org-level if not inheriting)
     */
    dailySessionLimit?: number | null;
    /**
     * Maximum number of concurrent agent sessions (overrides org-level if not inheriting)
     */
    maxConcurrentSessions?: number | null;
    /**
     * Budget alert thresholds (percentage of monthly budget)
     */
    alertThresholds?:
      | {
          /**
           * Threshold percentage (e.g., 50 for 50%)
           */
          percentage: number;
          /**
           * Whether notification has been sent for this threshold this month
           */
          notified?: boolean | null;
          /**
           * When the last notification was sent
           */
          lastNotifiedAt?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Email addresses to notify when budget thresholds are reached
     */
    alertEmails?:
      | {
          email: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Current month spend in USD (auto-calculated from agent sessions)
     */
    currentMonthSpend?: number | null;
    /**
     * Start date of current month tracking period
     */
    currentMonthStart?: string | null;
    /**
     * Number of agent sessions started today (auto-calculated)
     */
    todaySessionCount?: number | null;
    /**
     * Date for today session count tracking
     */
    todayDate?: string | null;
    /**
     * Number of currently active agent sessions
     */
    activeSessions?: number | null;
    /**
     * Whether monthly budget has been exceeded (prevents new sessions)
     */
    budgetExceeded?: boolean | null;
    /**
     * When the budget was exceeded
     */
    budgetExceededAt?: string | null;
    /**
     * Manually pause all agent operations until this date
     */
    pausedUntil?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  id: number;
  /**
   * Unique identifier for this agent (e.g., code-reviewer, test-writer)
   */
  agentId: string;
  /**
   * Human-readable name for this agent
   */
  name: string;
  /**
   * Description of what this agent does
   */
  description?: string | null;
  /**
   * List of tools available to this agent
   */
  tools?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Execution tier: light (stateless), worker (CF Worker), or sandbox (isolated)
   */
  tier?: ('light' | 'worker' | 'sandbox') | null;
  /**
   * AI model to use (e.g., claude-3-5-sonnet-20241022, overall)
   */
  model?: string | null;
  /**
   * Agent framework to use for execution
   */
  framework?: ('ai-sdk' | 'claude-agent-sdk' | 'openai-agents' | 'claude-code') | null;
  /**
   * System instructions for this agent (markdown format)
   */
  instructions?: string | null;
  /**
   * Maximum number of tool execution steps
   */
  maxSteps?: number | null;
  /**
   * Execution timeout in milliseconds (default: 5 minutes)
   */
  timeout?: number | null;
  /**
   * GitHub username for this agent (e.g., quinn-qa-bot)
   */
  githubUsername?: string | null;
  /**
   * GitHub Personal Access Token (encrypted in storage)
   */
  githubPat?: string | null;
  /**
   * Review role/persona for PRDO
   */
  reviewRole?: ('product' | 'qa' | 'security' | 'general') | null;
  /**
   * Agents this reviewer can escalate to (e.g., Quinn can escalate to Sam)
   */
  canEscalate?: (number | Agent)[] | null;
  /**
   * Organization/installation this agent is scoped to (leave empty for global)
   */
  org?: (number | null) | Installation;
  /**
   * Repository this agent is scoped to (leave empty for org-level or global)
   */
  repo?: (number | null) | Repo;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-events".
 */
export interface SyncEvent {
  id: number;
  eventType:
    | 'issue.created'
    | 'issue.updated'
    | 'issue.closed'
    | 'issue.reopened'
    | 'issue.deleted'
    | 'milestone.created'
    | 'milestone.updated'
    | 'milestone.closed'
    | 'milestone.deleted'
    | 'sync.full'
    | 'sync.push'
    | 'sync.pull';
  direction: 'local_to_github' | 'github_to_local' | 'bidirectional';
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'conflict';
  /**
   * Event payload data
   */
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Error message if failed
   */
  error?: string | null;
  /**
   * How the conflict was resolved
   */
  conflictResolution?: ('local_wins' | 'github_wins' | 'manual') | null;
  repo: number | Repo;
  /**
   * When the event was processed
   */
  processedAt?: string | null;
  /**
   * Number of retry attempts
   */
  retryCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "linear-integrations".
 */
export interface LinearIntegration {
  id: number;
  /**
   * User who connected this Linear integration
   */
  user: number | User;
  /**
   * Optional: Link to a specific repository
   */
  repo?: (number | null) | Repo;
  linearData: {
    /**
     * Linear organization ID
     */
    organizationId: string;
    /**
     * Linear organization name
     */
    organizationName: string;
    /**
     * Linear organization URL key
     */
    urlKey?: string | null;
    /**
     * Linear user ID
     */
    userId?: string | null;
    /**
     * Linear user email
     */
    userEmail?: string | null;
    /**
     * Linear team ID
     */
    teamId?: string | null;
    /**
     * Linear team name
     */
    teamName?: string | null;
  };
  /**
   * Linear webhook ID for this integration
   */
  webhookId?: string | null;
  /**
   * Webhook secret for signature verification (encrypted at rest)
   */
  webhookSecret?: string | null;
  /**
   * Whether this integration is active
   */
  active?: boolean | null;
  /**
   * Last successful sync timestamp
   */
  lastSyncAt?: string | null;
  /**
   * Result of last sync (counts, errors)
   */
  lastSyncResult?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  syncSettings?: {
    /**
     * Automatically sync on webhook events
     */
    autoSync?: boolean | null;
    /**
     * Sync Linear cycles as milestones
     */
    syncCycles?: boolean | null;
    /**
     * Sync Linear projects
     */
    syncProjects?: boolean | null;
    /**
     * Sync Linear labels
     */
    syncLabels?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "durable-objects".
 */
export interface DurableObject {
  id: number;
  /**
   * Type of Durable Object
   */
  type: 'org' | 'repo' | 'project' | 'pr' | 'issue';
  /**
   * Durable Object ID string
   */
  doId: string;
  /**
   * Human-readable reference: owner/repo#123
   */
  ref: string;
  /**
   * XState snapshot
   */
  state?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Last state update for detecting stale DOs
   */
  lastHeartbeat?: string | null;
  /**
   * Related installation/organization
   */
  org?: (number | null) | Installation;
  /**
   * Related repository
   */
  repo?: (number | null) | Repo;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connections".
 */
export interface Connection {
  id: number;
  /**
   * User who owns this connection
   */
  user: number | User;
  /**
   * Optional org-level connection
   */
  org?: (number | null) | Installation;
  /**
   * Integration name (PascalCase): GitHub, Slack, Linear
   */
  app: string;
  provider: 'native' | 'composio';
  /**
   * Provider-specific ID (composioUserId, installationId, etc.)
   */
  externalId: string;
  /**
   * Provider-specific metadata
   */
  externalRef?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'active' | 'expired' | 'revoked';
  /**
   * Granted permissions/scopes
   */
  scopes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * When the connection was established
   */
  connectedAt: string;
  /**
   * Token expiration for refresh
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tool-executions".
 */
export interface ToolExecution {
  id: number;
  /**
   * Durable Object ID that executed the tool
   */
  doId: string;
  /**
   * Tool name (e.g., GitHub.createPullRequest, Linear.createIssue)
   */
  tool: string;
  /**
   * Tool execution parameters
   */
  params:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Tool execution result (if successful)
   */
  result?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Error message if execution failed
   */
  error?: string | null;
  /**
   * Execution duration in milliseconds
   */
  durationMs: number;
  /**
   * When the tool was executed
   */
  executedAt: string;
  /**
   * User who initiated the tool execution
   */
  user: number | User;
  /**
   * Connection used for the tool execution
   */
  connection: number | Connection;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models".
 */
export interface Model {
  id: number;
  /**
   * OpenRouter model ID (e.g., anthropic/claude-3.5-sonnet)
   */
  modelId: string;
  /**
   * Human-readable model name
   */
  name?: string | null;
  /**
   * Model provider (e.g., anthropic, openai, google)
   */
  provider?: string | null;
  /**
   * Maximum context window in tokens
   */
  contextLength?: number | null;
  /**
   * Pricing: { prompt: number, completion: number } per token
   */
  pricing?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Capabilities: { vision: boolean, tools: boolean, streaming: boolean }
   */
  capabilities?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Last time model was synced from OpenRouter
   */
  lastSyncedAt?: string | null;
  /**
   * Curation status for UI filtering
   */
  status?: ('available' | 'recommended' | 'deprecated' | 'hidden') | null;
  /**
   * Model tier for categorization
   */
  tier?: ('fast' | 'balanced' | 'reasoning' | 'specialized') | null;
  /**
   * Use cases: ["coding", "research", "browser", "vision", etc.]
   */
  bestFor?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Internal notes about this model
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Maps model aliases (best, fast, cheap, overall) to actual models
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-defaults".
 */
export interface ModelDefault {
  id: number;
  /**
   * The model alias this default applies to
   */
  useCase: 'best' | 'fast' | 'cheap' | 'overall';
  /**
   * Optional task type for more specific defaults
   */
  taskType?: ('coding' | 'research' | 'browser' | 'general') | null;
  /**
   * The actual model to use for this use case
   */
  model: number | Model;
  /**
   * Optional org-level override
   */
  org?: (number | null) | Installation;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action:
    | 'agent_spawned'
    | 'agent_completed'
    | 'agent_failed'
    | 'agent_timeout'
    | 'code_generated'
    | 'branch_created'
    | 'commit_pushed'
    | 'pr_created'
    | 'pr_merged'
    | 'pr_closed'
    | 'review_started'
    | 'review_approved'
    | 'review_rejected'
    | 'changes_requested'
    | 'approval_required'
    | 'approval_granted'
    | 'approval_denied'
    | 'auto_approved'
    | 'cost_incurred'
    | 'budget_exceeded'
    | 'rate_limited'
    | 'rollback_triggered'
    | 'rollback_completed'
    | 'rollback_failed';
  status: 'success' | 'failed' | 'pending' | 'blocked';
  /**
   * Agent that performed this action
   */
  agent?: (number | null) | Agent;
  /**
   * Repository this action was performed on
   */
  repo?: (number | null) | Repo;
  /**
   * Pull request number if applicable
   */
  prNumber?: number | null;
  /**
   * Claude session ID for correlation
   */
  sessionId?: string | null;
  /**
   * Cost information for this action
   */
  cost?: {
    inputTokens?: number | null;
    outputTokens?: number | null;
    /**
     * Total cost in USD
     */
    totalUsd?: number | null;
  };
  /**
   * Risk assessment for this action
   */
  riskAssessment?: {
    level?: ('low' | 'medium' | 'high' | 'critical') | null;
    /**
     * Risk factors that contributed to this assessment
     */
    factors?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Whether this action touches critical paths (auth, payments, etc.)
     */
    touchesCriticalPath?: boolean | null;
  };
  /**
   * Additional details about this action
   */
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * List of files changed (for code actions)
   */
  filesChanged?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Code diff if applicable
   */
  diff?: string | null;
  /**
   * Rollback information
   */
  rollback?: {
    canRollback?: boolean | null;
    /**
     * Commit SHA to rollback to
     */
    rollbackCommit?: string | null;
    rolledBackAt?: string | null;
    rolledBackBy?: (number | null) | User;
  };
  /**
   * Approval information if this action required approval
   */
  approval?: {
    required?: boolean | null;
    approvedBy?: (number | null) | User;
    approvedAt?: string | null;
    /**
     * Reason for approval/denial
     */
    reason?: string | null;
  };
  /**
   * Error message if action failed
   */
  errorMessage?: string | null;
  /**
   * Duration of action in milliseconds
   */
  duration?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'installations';
        value: number | Installation;
      } | null)
    | ({
        relationTo: 'repos';
        value: number | Repo;
      } | null)
    | ({
        relationTo: 'sync-events';
        value: number | SyncEvent;
      } | null)
    | ({
        relationTo: 'linear-integrations';
        value: number | LinearIntegration;
      } | null)
    | ({
        relationTo: 'agents';
        value: number | Agent;
      } | null)
    | ({
        relationTo: 'durable-objects';
        value: number | DurableObject;
      } | null)
    | ({
        relationTo: 'connections';
        value: number | Connection;
      } | null)
    | ({
        relationTo: 'tool-executions';
        value: number | ToolExecution;
      } | null)
    | ({
        relationTo: 'models';
        value: number | Model;
      } | null)
    | ({
        relationTo: 'model-defaults';
        value: number | ModelDefault;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  githubId?: T;
  githubLogin?: T;
  githubAvatarUrl?: T;
  name?: T;
  workosUserId?: T;
  installations?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "installations_select".
 */
export interface InstallationsSelect<T extends boolean = true> {
  installationId?: T;
  accountId?: T;
  accountLogin?: T;
  accountType?: T;
  accountAvatarUrl?: T;
  permissions?: T;
  events?: T;
  repositorySelection?: T;
  suspendedAt?: T;
  users?: T;
  toolConfig?: T;
  approvalGates?:
    | T
    | {
        requireHumanApproval?: T;
        allowFullAutonomy?: T;
        maxBudgetPerDay?: T;
        maxAgentSpawnsPerHour?: T;
        riskThreshold?: T;
        criticalPaths?: T;
        autoApproveLabels?: T;
        requireApprovalLabels?: T;
        triggers?:
          | T
          | {
              labels?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              types?:
                | T
                | {
                    type?: T;
                    id?: T;
                  };
              filesChanged?:
                | T
                | {
                    pattern?: T;
                    id?: T;
                  };
              riskScore?: T;
            };
        approvers?:
          | T
          | {
              username?: T;
              id?: T;
            };
        teamApprovers?:
          | T
          | {
              team?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "repos_select".
 */
export interface ReposSelect<T extends boolean = true> {
  githubId?: T;
  name?: T;
  fullName?: T;
  owner?: T;
  private?: T;
  defaultBranch?: T;
  installation?: T;
  syncEnabled?: T;
  syncPath?: T;
  lastSyncAt?: T;
  syncStatus?: T;
  syncError?: T;
  reviewConfig?:
    | T
    | {
        enabled?: T;
        reviewers?:
          | T
          | {
              agent?: T;
              id?: T;
            };
        autoMerge?: T;
        requireHumanApproval?: T;
      };
  approvalGates?:
    | T
    | {
        inheritFromOrg?: T;
        requireHumanApproval?: T;
        allowFullAutonomy?: T;
        maxBudgetPerDay?: T;
        maxAgentSpawnsPerHour?: T;
        riskThreshold?: T;
        criticalPaths?: T;
        autoApproveLabels?: T;
        requireApprovalLabels?: T;
        triggers?:
          | T
          | {
              labels?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              types?:
                | T
                | {
                    type?: T;
                    id?: T;
                  };
              filesChanged?:
                | T
                | {
                    pattern?: T;
                    id?: T;
                  };
              riskScore?: T;
            };
        approvers?:
          | T
          | {
              username?: T;
              id?: T;
            };
        teamApprovers?:
          | T
          | {
              team?: T;
              id?: T;
            };
      };
  toolConfig?: T;
  costControls?:
    | T
    | {
        enabled?: T;
        inheritFromOrg?: T;
        monthlyBudget?: T;
        dailySessionLimit?: T;
        maxConcurrentSessions?: T;
        alertThresholds?:
          | T
          | {
              percentage?: T;
              notified?: T;
              lastNotifiedAt?: T;
              id?: T;
            };
        alertEmails?:
          | T
          | {
              email?: T;
              id?: T;
            };
        currentMonthSpend?: T;
        currentMonthStart?: T;
        todaySessionCount?: T;
        todayDate?: T;
        activeSessions?: T;
        budgetExceeded?: T;
        budgetExceededAt?: T;
        pausedUntil?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-events_select".
 */
export interface SyncEventsSelect<T extends boolean = true> {
  eventType?: T;
  direction?: T;
  status?: T;
  payload?: T;
  error?: T;
  conflictResolution?: T;
  repo?: T;
  processedAt?: T;
  retryCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "linear-integrations_select".
 */
export interface LinearIntegrationsSelect<T extends boolean = true> {
  user?: T;
  repo?: T;
  linearData?:
    | T
    | {
        organizationId?: T;
        organizationName?: T;
        urlKey?: T;
        userId?: T;
        userEmail?: T;
        teamId?: T;
        teamName?: T;
      };
  webhookId?: T;
  webhookSecret?: T;
  active?: T;
  lastSyncAt?: T;
  lastSyncResult?: T;
  syncSettings?:
    | T
    | {
        autoSync?: T;
        syncCycles?: T;
        syncProjects?: T;
        syncLabels?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  agentId?: T;
  name?: T;
  description?: T;
  tools?: T;
  tier?: T;
  model?: T;
  framework?: T;
  instructions?: T;
  maxSteps?: T;
  timeout?: T;
  githubUsername?: T;
  githubPat?: T;
  reviewRole?: T;
  canEscalate?: T;
  org?: T;
  repo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "durable-objects_select".
 */
export interface DurableObjectsSelect<T extends boolean = true> {
  type?: T;
  doId?: T;
  ref?: T;
  state?: T;
  lastHeartbeat?: T;
  org?: T;
  repo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connections_select".
 */
export interface ConnectionsSelect<T extends boolean = true> {
  user?: T;
  org?: T;
  app?: T;
  provider?: T;
  externalId?: T;
  externalRef?: T;
  status?: T;
  scopes?: T;
  connectedAt?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tool-executions_select".
 */
export interface ToolExecutionsSelect<T extends boolean = true> {
  doId?: T;
  tool?: T;
  params?: T;
  result?: T;
  error?: T;
  durationMs?: T;
  executedAt?: T;
  user?: T;
  connection?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models_select".
 */
export interface ModelsSelect<T extends boolean = true> {
  modelId?: T;
  name?: T;
  provider?: T;
  contextLength?: T;
  pricing?: T;
  capabilities?: T;
  lastSyncedAt?: T;
  status?: T;
  tier?: T;
  bestFor?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-defaults_select".
 */
export interface ModelDefaultsSelect<T extends boolean = true> {
  useCase?: T;
  taskType?: T;
  model?: T;
  org?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  status?: T;
  agent?: T;
  repo?: T;
  prNumber?: T;
  sessionId?: T;
  cost?:
    | T
    | {
        inputTokens?: T;
        outputTokens?: T;
        totalUsd?: T;
      };
  riskAssessment?:
    | T
    | {
        level?: T;
        factors?: T;
        touchesCriticalPath?: T;
      };
  details?: T;
  filesChanged?: T;
  diff?: T;
  rollback?:
    | T
    | {
        canRollback?: T;
        rollbackCommit?: T;
        rolledBackAt?: T;
        rolledBackBy?: T;
      };
  approval?:
    | T
    | {
        required?: T;
        approvedBy?: T;
        approvedAt?: T;
        reason?: T;
      };
  errorMessage?: T;
  duration?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}