/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    installations: Installation;
    repos: Repo;
    issues: Issue;
    milestones: Milestone;
    'sync-events': SyncEvent;
    'linear-integrations': LinearIntegration;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    milestones: {
      issues: 'issues';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    installations: InstallationsSelect<false> | InstallationsSelect<true>;
    repos: ReposSelect<false> | ReposSelect<true>;
    issues: IssuesSelect<false> | IssuesSelect<true>;
    milestones: MilestonesSelect<false> | MilestonesSelect<true>;
    'sync-events': SyncEventsSelect<false> | SyncEventsSelect<true>;
    'linear-integrations': LinearIntegrationsSelect<false> | LinearIntegrationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles?: ('admin' | 'user')[] | null;
  workosUserId?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  emailVerified?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "installations".
 */
export interface Installation {
  id: number;
  /**
   * GitHub App installation ID
   */
  installationId: number;
  /**
   * GitHub account ID (user or org)
   */
  accountId: number;
  /**
   * GitHub account login (username or org name)
   */
  accountLogin: string;
  accountType: 'User' | 'Organization';
  /**
   * GitHub avatar URL
   */
  accountAvatarUrl?: string | null;
  /**
   * Granted permissions from GitHub
   */
  permissions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Subscribed webhook events
   */
  events?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  repositorySelection?: ('all' | 'selected') | null;
  /**
   * When the installation was suspended
   */
  suspendedAt?: string | null;
  /**
   * Users connected to this installation
   */
  users?: (number | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "repos".
 */
export interface Repo {
  id: number;
  /**
   * GitHub repository ID
   */
  githubId: number;
  /**
   * Repository name (without owner)
   */
  name: string;
  /**
   * Full name (owner/repo)
   */
  fullName: string;
  /**
   * Repository owner (user or org login)
   */
  owner: string;
  private?: boolean | null;
  defaultBranch?: string | null;
  installation: number | Installation;
  /**
   * Whether to sync issues with GitHub
   */
  syncEnabled?: boolean | null;
  /**
   * Path to todo.mdx file in the repo
   */
  syncPath?: string | null;
  /**
   * Last successful sync timestamp
   */
  lastSyncAt?: string | null;
  syncStatus?: ('idle' | 'syncing' | 'error') | null;
  /**
   * Last sync error message
   */
  syncError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issues".
 */
export interface Issue {
  id: number;
  /**
   * Local issue ID (e.g., todo-abc)
   */
  localId: string;
  title: string;
  /**
   * Issue body/description (markdown)
   */
  body?: string | null;
  state: 'open' | 'closed';
  /**
   * Extended status (beyond GitHub open/closed)
   */
  status?: ('open' | 'in_progress' | 'closed') | null;
  /**
   * 0 = critical, 1 = high, 2 = medium, 3 = low, 4 = backlog
   */
  priority?: number | null;
  /**
   * Array of label names
   */
  labels?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of assignee logins
   */
  assignees?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * GitHub issue number
   */
  githubNumber?: number | null;
  /**
   * GitHub issue ID
   */
  githubId?: number | null;
  /**
   * GitHub issue URL
   */
  githubUrl?: string | null;
  /**
   * Issues this one depends on (blockers)
   */
  dependsOn?: (number | Issue)[] | null;
  repo: number | Repo;
  milestone?: (number | null) | Milestone;
  type?: ('task' | 'bug' | 'feature' | 'epic') | null;
  closedAt?: string | null;
  /**
   * Reason for closing the issue
   */
  closeReason?: string | null;
  /**
   * Linear integration metadata
   */
  linearData?: {
    /**
     * Linear issue ID
     */
    id?: string | null;
    /**
     * Linear issue identifier (e.g., TODO-123)
     */
    identifier?: string | null;
    /**
     * Linear state ID
     */
    stateId?: string | null;
    /**
     * Linear state name
     */
    stateName?: string | null;
    /**
     * Linear cycle ID
     */
    cycleId?: string | null;
    /**
     * Linear project ID
     */
    projectId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milestones".
 */
export interface Milestone {
  id: number;
  /**
   * Local milestone ID
   */
  localId: string;
  title: string;
  description?: string | null;
  state: 'open' | 'closed';
  /**
   * Due date for the milestone
   */
  dueOn?: string | null;
  /**
   * GitHub milestone number
   */
  githubNumber?: number | null;
  /**
   * GitHub milestone ID
   */
  githubId?: number | null;
  repo: number | Repo;
  issues?: {
    docs?: (number | Issue)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Linear integration metadata (for cycles)
   */
  linearData?: {
    /**
     * Linear cycle ID
     */
    id?: string | null;
    /**
     * Linear cycle number
     */
    number?: number | null;
    /**
     * Linear cycle start date
     */
    startsAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-events".
 */
export interface SyncEvent {
  id: number;
  eventType:
    | 'issue.created'
    | 'issue.updated'
    | 'issue.closed'
    | 'issue.reopened'
    | 'issue.deleted'
    | 'milestone.created'
    | 'milestone.updated'
    | 'milestone.closed'
    | 'milestone.deleted'
    | 'sync.full'
    | 'sync.push'
    | 'sync.pull';
  direction: 'local_to_github' | 'github_to_local' | 'bidirectional';
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'conflict';
  /**
   * Event payload data
   */
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Error message if failed
   */
  error?: string | null;
  /**
   * How the conflict was resolved
   */
  conflictResolution?: ('local_wins' | 'github_wins' | 'manual') | null;
  repo: number | Repo;
  /**
   * Related issue (if applicable)
   */
  issue?: (number | null) | Issue;
  /**
   * Related milestone (if applicable)
   */
  milestone?: (number | null) | Milestone;
  /**
   * When the event was processed
   */
  processedAt?: string | null;
  /**
   * Number of retry attempts
   */
  retryCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "linear-integrations".
 */
export interface LinearIntegration {
  id: number;
  /**
   * User who connected this Linear workspace
   */
  user: number | User;
  /**
   * Repository to sync Linear issues to (optional)
   */
  repo?: (number | null) | Repo;
  /**
   * Linear workspace information
   */
  linearData: {
    /**
     * Linear organization ID
     */
    organizationId: string;
    /**
     * Linear organization name
     */
    organizationName: string;
    /**
     * Linear workspace URL key
     */
    urlKey?: string | null;
    /**
     * Linear user ID
     */
    userId?: string | null;
    /**
     * Linear user email
     */
    userEmail?: string | null;
    /**
     * Linear team ID to sync (optional, syncs all teams if not set)
     */
    teamId?: string | null;
    /**
     * Linear team name
     */
    teamName?: string | null;
  };
  /**
   * Linear webhook ID for this integration
   */
  webhookId?: string | null;
  /**
   * Webhook secret for signature verification
   */
  webhookSecret?: string | null;
  /**
   * Whether this integration is active
   */
  active?: boolean | null;
  /**
   * Last successful sync timestamp
   */
  lastSyncAt?: string | null;
  /**
   * Result of last sync (counts, errors)
   */
  lastSyncResult?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Sync configuration
   */
  syncSettings?: {
    /**
     * Automatically sync on webhook events
     */
    autoSync?: boolean | null;
    /**
     * Sync Linear cycles as milestones
     */
    syncCycles?: boolean | null;
    /**
     * Sync Linear projects
     */
    syncProjects?: boolean | null;
    /**
     * Sync Linear labels
     */
    syncLabels?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'installations';
        value: number | Installation;
      } | null)
    | ({
        relationTo: 'repos';
        value: number | Repo;
      } | null)
    | ({
        relationTo: 'issues';
        value: number | Issue;
      } | null)
    | ({
        relationTo: 'milestones';
        value: number | Milestone;
      } | null)
    | ({
        relationTo: 'sync-events';
        value: number | SyncEvent;
      } | null)
    | ({
        relationTo: 'linear-integrations';
        value: number | LinearIntegration;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  workosUserId?: T;
  firstName?: T;
  lastName?: T;
  emailVerified?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "installations_select".
 */
export interface InstallationsSelect<T extends boolean = true> {
  installationId?: T;
  accountId?: T;
  accountLogin?: T;
  accountType?: T;
  accountAvatarUrl?: T;
  permissions?: T;
  events?: T;
  repositorySelection?: T;
  suspendedAt?: T;
  users?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "repos_select".
 */
export interface ReposSelect<T extends boolean = true> {
  githubId?: T;
  name?: T;
  fullName?: T;
  owner?: T;
  private?: T;
  defaultBranch?: T;
  installation?: T;
  syncEnabled?: T;
  syncPath?: T;
  lastSyncAt?: T;
  syncStatus?: T;
  syncError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issues_select".
 */
export interface IssuesSelect<T extends boolean = true> {
  localId?: T;
  title?: T;
  body?: T;
  state?: T;
  status?: T;
  priority?: T;
  labels?: T;
  assignees?: T;
  githubNumber?: T;
  githubId?: T;
  githubUrl?: T;
  dependsOn?: T;
  repo?: T;
  milestone?: T;
  type?: T;
  closedAt?: T;
  closeReason?: T;
  linearData?:
    | T
    | {
        id?: T;
        identifier?: T;
        stateId?: T;
        stateName?: T;
        cycleId?: T;
        projectId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milestones_select".
 */
export interface MilestonesSelect<T extends boolean = true> {
  localId?: T;
  title?: T;
  description?: T;
  state?: T;
  dueOn?: T;
  githubNumber?: T;
  githubId?: T;
  repo?: T;
  issues?: T;
  linearData?:
    | T
    | {
        id?: T;
        number?: T;
        startsAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-events_select".
 */
export interface SyncEventsSelect<T extends boolean = true> {
  eventType?: T;
  direction?: T;
  status?: T;
  payload?: T;
  error?: T;
  conflictResolution?: T;
  repo?: T;
  issue?: T;
  milestone?: T;
  processedAt?: T;
  retryCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "linear-integrations_select".
 */
export interface LinearIntegrationsSelect<T extends boolean = true> {
  user?: T;
  repo?: T;
  linearData?:
    | T
    | {
        organizationId?: T;
        organizationName?: T;
        urlKey?: T;
        userId?: T;
        userEmail?: T;
        teamId?: T;
        teamName?: T;
      };
  webhookId?: T;
  webhookSecret?: T;
  active?: T;
  lastSyncAt?: T;
  lastSyncResult?: T;
  syncSettings?:
    | T
    | {
        autoSync?: T;
        syncCycles?: T;
        syncProjects?: T;
        syncLabels?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}